#include "hash_tables.h"

/**
 * key_index - function finds the index or position of a key
 * in the hash table using the hash_djb2 of the prev task as hash function
 *@key: the value whose index is being looked for
 *@size: size of the table
 *
 * Return: returns the index of the key
 *
 * Description: The index is generated by taking the remainder when the
 * random index genereated by the hash function is divided by the hash
 * table's array size. it is obvious this will result in collision, which
 * is what we want so that we can see how to handle collision using index
 * chaining
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int index;

	index = hash_djb2(key) % size;
	return (index);
}
